export const dishFormDefaultValues = Object.freeze({
  name: "",
  price: "",
  cuisine: "",
  category: "",
  description: "",
  ingredients: [],
  isVegan: false,
  image: "",
  weight: "",
  cookTimeInMinutes: "",
  spiceLevel: 0,
  nutrition: {
    calories: "",
    protein: "",
    fats: "",
    carbohydrates: "",
  },
  isAvailable: true,
});
