export const carsData = [
  {
    id: 9611162,
    year: 2020,
    make: "Audi",
    model: "A7",
    type: "Sedan",
    img: [
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/rMpl8gJG-1uIeyqOJlv-(edit).jpg?t=164877816051",
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/rMpl8gJG-1uIeyqOJlv-(edit).jpg?t=164877816051",
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/rMpl8gJG-1uIeyqOJlv-(edit).jpg?t=164877816051",
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/rMpl8gJG-1uIeyqOJlv-(edit).jpg?t=164877816051",
      "https://media.carsandbids.com/cdn-cgi/image/width=2080,quality=70/7a0a3c6148108c9c64425dd85e0181fa3cccb652/photos/rMpl8gJG-1uIeyqOJlv-(edit).jpg?t=164877816051",
    ],

    description:
      "~30,600 Miles, 453-hp V8, Some Modifications, Reviewed by Alanis King",
    fuelConsumption: "11.8",
    engineSize: "3.0L V6",
    accessories: [
      "Airscarf neck-level heating",
      "Harman Kardon premium audio system",
      "Active Body Control suspension",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Retractable hardtop roof",
      "Multi-contour seats",
    ],
    price: 12200,
    rentalCompany: "Exquisite Car Rentals",
    address: "789 Example Boulevard, Kyiv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
    mileage: 1035,
    createdAt: new Date(),
  },
  {
    id: 91621562,
    year: 2016,
    make: "Mercedes-Benz",
    model: "A-Class",
    type: "Hatchback",
    img: [
      "https://img-ik.cars.co.za/news-site-za/images/2016/05/DSC_5214.jpg",
      "https://img-ik.cars.co.za/news-site-za/images/2016/05/DSC_5214.jpg",
      "https://img-ik.cars.co.za/news-site-za/images/2016/05/DSC_5214.jpg",
      "https://img-ik.cars.co.za/news-site-za/images/2016/05/DSC_5214.jpg",
    ],
    description: "Twin-Turbo V6, Emerald Green Metallic, Unmodified",
    fuelConsumption: "7.8",
    engineSize: "2.0L I6",
    accessories: [
      "Airscarf neck-level heating",
      "Harman Kardon premium audio system",
      "Active Body Control suspension",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Retractable hardtop roof",
      "Multi-contour seats",
    ],
    price: 12100,
    rentalCompany: "Exquisite Car Rentals",
    address: "789 Example Boulevard, Kyiv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
    mileage: 2383,
    createdAt: new Date(),
  },
  {
    id: 963030,
    year: 2020,
    make: "Bentley",
    model: "Continental",
    type: "Convertible",
    img: [
      "https://vehicle-images.dealerinspire.com/b024-110009518/SCBDG4ZG5LC083757/1de9eefcf180b16cc6354462b329e6d2.jpg",
      "https://vehicle-images.dealerinspire.com/b024-110009518/SCBDG4ZG5LC083757/1de9eefcf180b16cc6354462b329e6d2.jpg",
      "https://vehicle-images.dealerinspire.com/b024-110009518/SCBDG4ZG5LC083757/1de9eefcf180b16cc6354462b329e6d2.jpg",
    ],
    description:
      "1 Owner, Dual-Motor AWD, Premium Upgrades Package, Texas-Owned",
    fuelConsumption: "22.5",
    engineSize: "5.0L V8",
    accessories: [
      "Mulliner Driving Specification",
      "Naim for Bentley premium audio system",
      "Heated steering wheel",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Air suspension",
      "Automatic convertible roof",
    ],
    price: 12350,
    rentalCompany: "Luxury Car Rentals",
    address: "567 Example Street, Lviv, Ukraine",
    rentalConditions:
      "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 2311,
    createdAt: new Date(),
  },
  {
    id: 9262429,
    year: 2023,
    make: "Lamborghini",
    model: "Huracan",
    type: "Sport car",
    img: [
      "https://hips.hearstapps.com/hmg-prod/images/2022-lamborghini-huracan-tecnica-101-1657303967.jpg?crop=0.700xw:0.790xh;0.0717xw,0.183xh&resize=640:*",
      "https://hips.hearstapps.com/hmg-prod/images/2022-lamborghini-huracan-tecnica-101-1657303967.jpg?crop=0.700xw:0.790xh;0.0717xw,0.183xh&resize=640:*",
      "https://hips.hearstapps.com/hmg-prod/images/2022-lamborghini-huracan-tecnica-101-1657303967.jpg?crop=0.700xw:0.790xh;0.0717xw,0.183xh&resize=640:*",
      "https://hips.hearstapps.com/hmg-prod/images/2022-lamborghini-huracan-tecnica-101-1657303967.jpg?crop=0.700xw:0.790xh;0.0717xw,0.183xh&resize=640:*",
    ],
    description: "Gated 6-Speed Manual, 571-hp V12, AWD, Some Modifications",
    fuelConsumption: "25.0",
    engineSize: "6.5L V12",
    accessories: [
      "Carbon-fiber body panels",
      "Alcantara upholstery",
      "Lamborghini Infotainment System",
    ],
    functionalities: [
      "All-Wheel Drive",
      "Electronic Stability Control",
      "Retractable soft-top roof",
    ],
    price: 12600,
    rentalCompany: "Supercar Rentals",
    address: "321 Example Road, Kharkiv, Ukraine",
    rentalConditions:
      "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 1832,
    createdAt: new Date(),
  },
  {
    id: 9651345,
    year: 2021,
    make: "BMW",
    model: "M4",
    type: "Sport car",
    img: [
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bmw-m4-2021-5-jpg-1625677202.jpg",
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bmw-m4-2021-5-jpg-1625677202.jpg",
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bmw-m4-2021-5-jpg-1625677202.jpg",
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/bmw-m4-2021-5-jpg-1625677202.jpg",
    ],

    description:
      "6-Speed Manual, M Sport Package, 3.0-Liter 6-Cylinder, Unmodified",
    fuelConsumption: "13.2",
    engineSize: "3.0 I6",
    accessories: [
      "Aluminum space frame",
      "Nappa leather upholstery",
      "Harman Kardon audio system",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Dynamic Stability Control",
      "Power-operated soft-top roof",
    ],
    price: 12300,
    rentalCompany: "Exquisite Car Rentals",
    address: "654 Example Circle, Zaporizhzhia, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
    mileage: 6993,
    createdAt: new Date(),
  },
  {
    id: 961825248,
    year: 2020,
    make: "Land Rover",
    model: "Range Rover Velar",
    type: "SUV",
    img: [
      "https://img.automoto.ua/overview/land-rover-range-rover-velar-2020-a85-huge-1647.jpg",
      "https://img.automoto.ua/overview/land-rover-range-rover-velar-2020-a85-huge-1647.jpg",
      "https://img.automoto.ua/overview/land-rover-range-rover-velar-2020-a85-huge-1647.jpg",
      "https://img.automoto.ua/overview/land-rover-range-rover-velar-2020-a85-huge-1647.jpg",
      "https://img.automoto.ua/overview/land-rover-range-rover-velar-2020-a85-huge-1647.jpg",
    ],
    description: "1 Owner, Turbodiesel V6, 4WD, Texas-Owned, Unmodified",
    fuelConsumption: "11.8",
    engineSize: "3.0L V6",
    accessories: [
      "Premium Windsor leather seats",
      "Meridian surround sound system",
      "Adaptive Dynamics suspension",
    ],
    functionalities: [
      "All-Wheel Drive",
      "Terrain Response 2 system",
      "Power-operated gesture tailgate",
    ],
    price: 12250,
    rentalCompany: "Luxury SUV Rentals",
    address: "654 Example Street, Lviv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 2356,
    createdAt: new Date(),
  },
  {
    id: 95812,
    year: 2008,
    make: "Buick",
    model: "Enclave",
    type: "SUV",
    img: [
      "https://i.infocar.ua/i/2/1276/100983/1920x.jpg",
      "https://i.infocar.ua/i/2/1276/100983/1920x.jpg",
      "https://i.infocar.ua/i/2/1276/100983/1920x.jpg",
      "https://i.infocar.ua/i/2/1276/100983/1920x.jpg",
      "https://i.infocar.ua/i/2/1276/100983/1920x.jpg",
    ],
    description:
      "V6 Power, Final-Year Model, Some Modifications, Engine Replaced in 2023",
    fuelConsumption: "10.5",
    engineSize: "3.6L V6",
    accessories: ["Leather seats", "Panoramic sunroof", "Premium audio system"],
    functionalities: [
      "Power liftgate",
      "Remote start",
      "Blind-spot monitoring",
    ],
    price: 1240,
    rentalCompany: "Luxury Car Rentals",
    address: "123 Example Street, Kiev, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit required",
    mileage: 5858,
    createdAt: new Date(),
  },
  {
    id: 961662,
    year: 2004,
    make: "Mercedes-Benz",
    model: "SL-Class",
    type: "Convertible",
    img: [
      "https://carsales.pxcrush.net/carsales/cars/private/599amily7tsii2xlbfed2g9gk.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900%2C600",
      "https://carsales.pxcrush.net/carsales/cars/private/599amily7tsii2xlbfed2g9gk.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900%2C600",
      "https://carsales.pxcrush.net/carsales/cars/private/599amily7tsii2xlbfed2g9gk.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900%2C600",
      "https://carsales.pxcrush.net/carsales/cars/private/599amily7tsii2xlbfed2g9gk.jpg?pxc_method=gravityfill&pxc_bgtype=self&pxc_size=900%2C600",
    ],
    description:
      "V8 Power, Arctic White, Royal Blue Interior, Mostly Unmodified",
    fuelConsumption: "11.8",
    engineSize: "5.0L V8",
    accessories: [
      "Airscarf neck-level heating",
      "Harman Kardon premium audio system",
      "Active Body Control suspension",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Retractable hardtop roof",
      "Multi-contour seats",
    ],
    price: 1275,
    rentalCompany: "Exquisite Car Rentals",
    address: "789 Example Boulevard, Kyiv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and proof of insurance required",
    mileage: 5722,
    createdAt: new Date(),
  },
  {
    id: 962429,
    year: 2009,
    make: "Lamborghini",
    model: "Murcielago",
    type: "Convertible",
    img: [
      "https://www.westcoastexoticcars.com/imagetag/82/main/l/Used-2009-Lamborghini-Murcielago-1610053605.jpg",
      "https://www.westcoastexoticcars.com/imagetag/82/main/l/Used-2009-Lamborghini-Murcielago-1610053605.jpg",
      "https://www.westcoastexoticcars.com/imagetag/82/main/l/Used-2009-Lamborghini-Murcielago-1610053605.jpg",
      "https://www.westcoastexoticcars.com/imagetag/82/main/l/Used-2009-Lamborghini-Murcielago-1610053605.jpg",
    ],
    description:
      "~2,600 Miles, Blu Fontus, Full Exterior Carbon Pack, Reviewed by Kennan Rolsen",
    fuelConsumption: "25.0",
    engineSize: "6.5L V12",
    accessories: [
      "Carbon-fiber body panels",
      "Alcantara upholstery",
      "Lamborghini Infotainment System",
    ],
    functionalities: [
      "All-Wheel Drive",
      "Electronic Stability Control",
      "Retractable soft-top roof",
    ],
    price: 12500,
    rentalCompany: "Supercar Rentals",
    address: "321 Example Road, Kharkiv, Ukraine",
    rentalConditions:
      "Minimum age: 30\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 5832,
    createdAt: new Date(),
  },
  {
    id: 9655135,
    year: 1998,
    make: "Chevrolet",
    model: "Camaro",
    type: "Convertible",
    img: [
      "https://upload.wikimedia.org/wikipedia/commons/3/30/1993ChevroletCamaroZ28-001.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/30/1993ChevroletCamaroZ28-001.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/30/1993ChevroletCamaroZ28-001.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/30/1993ChevroletCamaroZ28-001.jpg",
    ],
    description:
      "~6,100 Miles, 1 of 25 SC Stage II Units in 2020, 6-Speed Manual, 1,103-hp Supercharged V8",
    fuelConsumption: "13.5",
    engineSize: "5.7L V8",
    accessories: [
      "Leather upholstery",
      "Bose premium sound system",
      "Performance suspension",
    ],
    functionalities: [
      "Rear-Wheel Drive",
      "Limited-slip differential",
      "Power-operated convertible top",
    ],
    price: 12200,
    rentalCompany: "Muscle Car Rentals",
    address: "123 Example Street, Lviv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 6330,
    createdAt: new Date(),
  },
  {
    id: 9666430,
    year: 2020,
    make: "Chrysler",
    model: "Voyager",
    type: "Van/Minivan",
    img: [
      "https://cdn.carbuzz.com/gallery-images/1600/669000/400/669413.jpg",
      "https://cdn.carbuzz.com/gallery-images/1600/669000/400/669413.jpg",
      "https://cdn.carbuzz.com/gallery-images/1600/669000/400/669413.jpg",
    ],
    description:
      "~50,200 Miles, Classic Yellow, Southern-Owned, Mostly Unmodified",
    fuelConsumption: "8.2",
    engineSize: "3.6L V6",
    accessories: [
      "Stow 'n Go seating",
      "Uconnect infotainment system",
      "Blind Spot Monitoring",
    ],
    functionalities: [
      "Front-Wheel Drive",
      "Electronic Stability Control",
      "Power sliding side doors",
    ],
    price: 12100,
    rentalCompany: "Family Car Rentals",
    address: "789 Example Boulevard, Odesa, Ukraine",
    rentalConditions:
      "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 5807,
    createdAt: new Date(),
  },
  {
    id: 9618348,
    year: 2020,
    make: "Land Rover",
    model: "Range Rover Sport",
    type: "SUV",
    img: [
      "https://a.allegroimg.com/original/11c6bb/4bad5de845499dae0a7081e22a64/Land-Rover-Range-Rover-Sport-SVR-5-0-V8-S-C-550KM",
      "https://a.allegroimg.com/original/11c6bb/4bad5de845499dae0a7081e22a64/Land-Rover-Range-Rover-Sport-SVR-5-0-V8-S-C-550KM",
      "https://a.allegroimg.com/original/11c6bb/4bad5de845499dae0a7081e22a64/Land-Rover-Range-Rover-Sport-SVR-5-0-V8-S-C-550KM",
      "https://a.allegroimg.com/original/11c6bb/4bad5de845499dae0a7081e22a64/Land-Rover-Range-Rover-Sport-SVR-5-0-V8-S-C-550KM",
    ],
    description: "1 Owner, Turbodiesel V6, 4WD, Texas-Owned, Unmodified",
    fuelConsumption: "11.8",
    engineSize: "3.0L V6",
    accessories: [
      "Premium Windsor leather seats",
      "Meridian surround sound system",
      "Adaptive Dynamics suspension",
    ],
    functionalities: [
      "All-Wheel Drive",
      "Terrain Response 2 system",
      "Power-operated gesture tailgate",
    ],
    price: 12300,
    rentalCompany: "Luxury SUV Rentals",
    address: "654 Example Street, Lviv, Ukraine",
    rentalConditions:
      "Minimum age: 25\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 4856,
    createdAt: new Date(),
  },
  {
    id: 9684330,
    year: 2020,
    make: "Kia",
    model: "Rio",
    type: "Sedan, Hatchback",
    img: [
      "https://media.ed.edmunds-media.com/kia/rio/2018/oem/2018_kia_rio_sedan_ex_fq_oem_1_1600.jpg",
      "https://media.ed.edmunds-media.com/kia/rio/2018/oem/2018_kia_rio_sedan_ex_fq_oem_1_1600.jpg",
      "https://media.ed.edmunds-media.com/kia/rio/2018/oem/2018_kia_rio_sedan_ex_fq_oem_1_1600.jpg",
    ],
    description:
      "Dual-Motor AWD, First Edition Package, Ultra-Fast 800V DC Charging",
    fuelConsumption: "6.2",
    engineSize: "1.6L 4-cylinder",
    accessories: [
      "Apple CarPlay and Android Auto integration",
      "Smart Key with Push Button Start",
      "Automatic climate control",
    ],
    functionalities: [
      "Front-Wheel Drive",
      "Electronic Stability Control",
      "Rearview camera",
    ],
    price: 1250,
    rentalCompany: "Economy Car Rentals",
    address: "321 Example Lane, Kharkiv, Ukraine",
    rentalConditions:
      "Minimum age: 21\nValid driver's license\nSecurity deposit and insurance required",
    mileage: 6234,
    createdAt: new Date(),
  },
];
